# Site settings
title: Ashley S Doane
email: ashley.doane@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Ashley S Doane profile, research interests, publications
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bassounds.github.io" # the base hostname & protocol for your site
twitter_username: ashleydoane
github_username:  bassounds

# Build settings
markdown: kramdown
